apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

images:
  - name: lexmarkkubernetes/db_microservice
    newTag: latest-prod  # Use a development-specific image tag

patches:
  - target:
      kind: Deployment
      name: mongo-db
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mongo-db
      spec:
        replicas: 1  # Can be adjusted for dev; keeping it 1 for simplicity
        template:
          spec:
            containers:
              - name: mongo-db
